version: "3.9"
services:
  app:
    image: demo_server:latest
    volumes:
      - ./app:/home
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
      - ./static:/var/www/app/static/
    ports:
      - "443:443"
    depends_on:
      - app
